/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestRouteImport } from './routes/test'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductCreateRouteImport } from './routes/product.create'
import { Route as ProductIdRouteImport } from './routes/product.$id'
import { Route as ApiProductsRouteImport } from './routes/api/products'
import { Route as ProductEditIdRouteImport } from './routes/product.edit.$id'
import { Route as ApiProductsIdRouteImport } from './routes/api/products.$id'

const TestRoute = TestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductCreateRoute = ProductCreateRouteImport.update({
  id: '/product/create',
  path: '/product/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProductsRoute = ApiProductsRouteImport.update({
  id: '/api/products',
  path: '/api/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductEditIdRoute = ProductEditIdRouteImport.update({
  id: '/product/edit/$id',
  path: '/product/edit/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProductsIdRoute = ApiProductsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiProductsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/products': typeof ProductsRoute
  '/test': typeof TestRoute
  '/api/products': typeof ApiProductsRouteWithChildren
  '/product/$id': typeof ProductIdRoute
  '/product/create': typeof ProductCreateRoute
  '/api/products/$id': typeof ApiProductsIdRoute
  '/product/edit/$id': typeof ProductEditIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/products': typeof ProductsRoute
  '/test': typeof TestRoute
  '/api/products': typeof ApiProductsRouteWithChildren
  '/product/$id': typeof ProductIdRoute
  '/product/create': typeof ProductCreateRoute
  '/api/products/$id': typeof ApiProductsIdRoute
  '/product/edit/$id': typeof ProductEditIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/products': typeof ProductsRoute
  '/test': typeof TestRoute
  '/api/products': typeof ApiProductsRouteWithChildren
  '/product/$id': typeof ProductIdRoute
  '/product/create': typeof ProductCreateRoute
  '/api/products/$id': typeof ApiProductsIdRoute
  '/product/edit/$id': typeof ProductEditIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/products'
    | '/test'
    | '/api/products'
    | '/product/$id'
    | '/product/create'
    | '/api/products/$id'
    | '/product/edit/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/products'
    | '/test'
    | '/api/products'
    | '/product/$id'
    | '/product/create'
    | '/api/products/$id'
    | '/product/edit/$id'
  id:
    | '__root__'
    | '/'
    | '/products'
    | '/test'
    | '/api/products'
    | '/product/$id'
    | '/product/create'
    | '/api/products/$id'
    | '/product/edit/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProductsRoute: typeof ProductsRoute
  TestRoute: typeof TestRoute
  ApiProductsRoute: typeof ApiProductsRouteWithChildren
  ProductIdRoute: typeof ProductIdRoute
  ProductCreateRoute: typeof ProductCreateRoute
  ProductEditIdRoute: typeof ProductEditIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/create': {
      id: '/product/create'
      path: '/product/create'
      fullPath: '/product/create'
      preLoaderRoute: typeof ProductCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/products': {
      id: '/api/products'
      path: '/api/products'
      fullPath: '/api/products'
      preLoaderRoute: typeof ApiProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/edit/$id': {
      id: '/product/edit/$id'
      path: '/product/edit/$id'
      fullPath: '/product/edit/$id'
      preLoaderRoute: typeof ProductEditIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/products/$id': {
      id: '/api/products/$id'
      path: '/$id'
      fullPath: '/api/products/$id'
      preLoaderRoute: typeof ApiProductsIdRouteImport
      parentRoute: typeof ApiProductsRoute
    }
  }
}

interface ApiProductsRouteChildren {
  ApiProductsIdRoute: typeof ApiProductsIdRoute
}

const ApiProductsRouteChildren: ApiProductsRouteChildren = {
  ApiProductsIdRoute: ApiProductsIdRoute,
}

const ApiProductsRouteWithChildren = ApiProductsRoute._addFileChildren(
  ApiProductsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProductsRoute: ProductsRoute,
  TestRoute: TestRoute,
  ApiProductsRoute: ApiProductsRouteWithChildren,
  ProductIdRoute: ProductIdRoute,
  ProductCreateRoute: ProductCreateRoute,
  ProductEditIdRoute: ProductEditIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
